In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')
df

,sentence_1,sentence_2
0,Hi I am Rama. I am here only,here only in EY
1,Data is the new oil but clean data is gold,"Without clean data, oil becomes useless"
2,Power BI and Tableau are data visualization tools,Power BI connects to multiple sources
3,Python is great for automation,Automation is the key to productivity
4,Practice makes a data analyst perfect,Practice with real datasets makes you perfect

In [7]:
df['sentence1'] = df['sentence_1'].str.split(' ')
df['sentence2'] = df['sentence_2'].str.split(' ')
df[['sentence1','sentence2']]

,sentence1,sentence2
0,"[Hi, I, am, Rama., I, am, here, only]","[here, only, in, EY]"
1,"[Data, is, the, new, oil, but, clean, data, is...","[Without, clean, data,, oil, becomes, useless]"
2,"[Power, BI, and, Tableau, are, data, visualiza...","[Power, BI, connects, to, multiple, sources]"
3,"[Python, is, great, for, automation]","[Automation, is, the, key, to, productivity]"
4,"[Practice, makes, a, data, analyst, perfect]","[Practice, with, real, datasets, makes, you, p..."

In [9]:
def find_common_words(row):
    return set(row['sentence1']) & set(row['sentence2'])
df['common_words'] = df.apply(find_common_words, axis = 1)
df['common_words']

0                  {here, only}
1                  {clean, oil}
2                   {Power, BI}
3                          {is}
4    {Practice, perfect, makes}
Name: common_words, dtype: object

In [10]:
def count_common_words(row):
    result = {}

    for word in row['common_words']:
        count = row['sentence2'].count(word)
        result[word] = count
        
    return result

In [12]:
df['final_output'] = df.apply(count_common_words, axis = 1)
df['final_output']

0                       {'here': 1, 'only': 1}
1                       {'clean': 1, 'oil': 1}
2                        {'Power': 1, 'BI': 1}
3                                    {'is': 1}
4    {'Practice': 1, 'perfect': 1, 'makes': 1}
Name: final_output, dtype: object