In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('data.csv')
df

,user_id,title,seconds,ts,user_name
0,14,The Prestige,881,2025-10-21 00:00:00,Lisa Palmer
1,19,Titanic,1588,2025-10-21 00:10:00,Ashley Benjamin
2,91,The Lion King,121,2025-10-21 00:20:00,Elizabeth Walls
3,81,The Wolf of Wall Street,992,2025-10-21 00:30:00,Michael Hamilton
4,9,The Godfather,1666,2025-10-21 00:40:00,Jessica Schmitt
...,...,...,...,...,...
495,22,Pulp Fiction,945,2025-10-24 10:30:00,Michelle Dennis
496,94,The Shawshank Redemption,1235,2025-10-24 10:40:00,Daniel Randall
497,67,Forrest Gump,1136,2025-10-24 10:50:00,Christopher Pratt
498,12,Forrest Gump,1744,2025-10-24 11:00:00,Robert Fowler
499,16,Schindler's List,1126,2025-10-24 11:10:00,Cynthia Roberts

In [13]:
df['ts'] = pd.to_datetime(df['ts'], errors = 'coerce')
df['hour'] = df['ts'].dt.hour
df['date'] = df['ts'].dt.date
df

,user_id,title,seconds,ts,user_name,hour,date
0,14,The Prestige,881,2025-10-21 00:00:00,Lisa Palmer,0,2025-10-21
1,19,Titanic,1588,2025-10-21 00:10:00,Ashley Benjamin,0,2025-10-21
2,91,The Lion King,121,2025-10-21 00:20:00,Elizabeth Walls,0,2025-10-21
3,81,The Wolf of Wall Street,992,2025-10-21 00:30:00,Michael Hamilton,0,2025-10-21
4,9,The Godfather,1666,2025-10-21 00:40:00,Jessica Schmitt,0,2025-10-21
...,...,...,...,...,...,...,...
495,22,Pulp Fiction,945,2025-10-24 10:30:00,Michelle Dennis,10,2025-10-24
496,94,The Shawshank Redemption,1235,2025-10-24 10:40:00,Daniel Randall,10,2025-10-24
497,67,Forrest Gump,1136,2025-10-24 10:50:00,Christopher Pratt,10,2025-10-24
498,12,Forrest Gump,1744,2025-10-24 11:00:00,Robert Fowler,11,2025-10-24
499,16,Schindler's List,1126,2025-10-24 11:10:00,Cynthia Roberts,11,2025-10-24

In [19]:
new_df = df[df['date'] == pd.to_datetime('2025-10-21').date()]
new_df

,user_id,title,seconds,ts,user_name,hour,date
0,14,The Prestige,881,2025-10-21 00:00:00,Lisa Palmer,0,2025-10-21
1,19,Titanic,1588,2025-10-21 00:10:00,Ashley Benjamin,0,2025-10-21
2,91,The Lion King,121,2025-10-21 00:20:00,Elizabeth Walls,0,2025-10-21
3,81,The Wolf of Wall Street,992,2025-10-21 00:30:00,Michael Hamilton,0,2025-10-21
4,9,The Godfather,1666,2025-10-21 00:40:00,Jessica Schmitt,0,2025-10-21
...,...,...,...,...,...,...,...
139,41,Titanic,385,2025-10-21 23:10:00,Bonnie Mason,23,2025-10-21
140,29,Forrest Gump,1551,2025-10-21 23:20:00,Jacqueline Johnson,23,2025-10-21
141,79,Inception,146,2025-10-21 23:30:00,Mark Roberson MD,23,2025-10-21
142,84,The Matrix,996,2025-10-21 23:40:00,Seth Perez,23,2025-10-21
143,60,The Avengers,583,2025-10-21 23:50:00,Jessica Ramirez,23,2025-10-21

In [31]:
result = (new_df
          .groupby('hour')['seconds']
          .sum()
          .sort_values(ascending=False)
          .head(5)
)
result

hour
17    8022
6     7316
21    7034
20    6684
8     6546
Name: seconds, dtype: int64